#!/bin/sh

# vim: ts=4:sw=4:et:ft=sh
# -*- mode: sh; indent-tabs-mode: nil; tab-width: 4 -*-
# code: language=sh insertSpaces=true tabSize=4

# https://github.com/deoren/config-files

# Redirect output to stderr.
exec 1>&2


##################################################################
# Run linters to ensure consistent Go code formatting and to
# help prevent basic problems from creeping in
##################################################################

# https://github.com/go-goracle/goracle#pre-commit
#set -e
# output="$(gofmt -l "$@")"

# if [ -n "$output" ]; then
#     echo >&2 "Go files must be formatted with gofmt. Please run:"
#     for f in $output; do
#         echo >&2 "  gofmt -w $PWD/$f"
#     done
#     exit 1
# fi

# Force gofmt "matches" to generate non-zero exit code
# This doesn't appear to work well with Git for Windows / Git Bash
#
# diff: /dev/fd/63: No such file or directory
# diff: /dev/fd/62: No such file or directory
#
#diff -u <(echo -n) <(gofmt -l -e -d .)

# go get -u golang.org/x/lint/golint
golint -set_exit_status ./...

go vet ./...

# go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
# https://github.com/golangci/golangci-lint#supported-linters
golangci-lint run \
    -E goimports \
    -E gosec \
    -E stylecheck \
    -E goconst \
    -E depguard \
    -E prealloc

# go get -u honnef.co/go/tools/cmd/staticcheck
staticcheck ./...


# Sample hook script provided by Git for Windows
# Kept because it looks useful
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
    # Note that the use of brackets around a tr range is ok here, (it's
    # even required, for portability to Solaris 10's /usr/bin/tr), since
    # the square bracket bytes happen to fall in the designated range.
    test $(git diff --cached --name-only --diff-filter=A -z $against |
      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
    cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
